---
###
# Installation of Debian packaged tools.
###

- name: "Debian Tools | Install apt package pre-requisites."
  apt:
    name: "{{ ddhn_debian_tools }}"
    state: "latest"

- name: "Debian Tools | Add desktop icons for Debian tools."
  copy:
    src: "/usr/share/applications/{{ item }}.desktop"
    dest: "/home/{{ ddhn_account_name }}/Desktop/{{ item }}.desktop"
    owner: "{{ ddhn_account_name }}"
    group: "{{ ddhn_account_name }}"
    mode: preserve
    remote_src: yes
  with_items: "{{ ddhn_debian_icons }}"

- name: "Debian Tools | Set executable permissions for Desktop icons."
  ansible.builtin.file:
    path: "/home/{{ ddhn_account_name }}/Desktop/{{ item }}.desktop"
    state: file
    mode: "u+x,g+x,o+x"
  with_items: "{{ ddhn_debian_icons }}"
