---
# desktop Environment setup for DDHN tools

- name: "Desktop | Create Nemo config directory."
  file:
    path: "/home/{{ ddhn.setup.limited_account.name }}/.config/autostart"
    state: directory
    mode: '0755'
    owner: "{{ ddhn.setup.limited_account.name }}"
    group: "{{ ddhn.setup.limited_account.name }}"

- name: "Desktop | Add hidden desktop file for Nemo and icons"
  copy:
    src: "files/home/.config/autostart/nemo-autostart-with-gnome.desktop"
    dest: "/home/{{ ddhn.setup.limited_account.name }}/.config/autostart/nemo-autostart-with-gnome.desktop"
