---
# Main task entry point for viper.tools
- name: "ViPER TOOLS | Install MediaArea tools."
  import_tasks: mediaarea/main.yml

- name: "ViPER TOOLS | Install Debian Tools."
  import_tasks: debTools.yml

- name: "ViPER TOOLS | Install JHOVE."
  import_tasks: jhove.yml

- name: "ViPER TOOLS | Install DROID."
  import_tasks: droid.yml

- name: "ViPER TOOLS | Install Tika."
  import_tasks: tika.yml

- name: "ViPER TOOLS | Install veraPDF."
  import_tasks: verapdf.yml
