---
# General tool installation tasks, repeatable per tool

- name: "TOOL {{ item.name }} | Download source from GitHub."
  git:
    repo: "{{ item.source.git }}"
    dest: "{{ item.dests.src }}"
    version: "{{ item.source.tag }}"

- name: "TOOL {{ item.name }} | Create target directory for install"
  file:
    path: "{{ item.dests.lib }}"
    state: directory
    mode: '0755'

- name: "TOOL {{ item.name }} | Copy icon file"
  copy:
    src: "files{{ viper_icons_share }}/{{ item.icon }}"
    dest: "{{ viper_icons_share }}/{{ item.icon }}"

- name: "TOOL {{ item.name }} | Create shared desktop file from template"
  template:
    src: "usr/share/applications/template.desktop"
    dest: "{{ viper_apps_share }}/{{ item.name }}.desktop"
    mode: a+x

- name: "TOOL {{ item.name }} | Create user desktop file from template"
  template:
    src: "usr/share/applications/template.desktop"
    dest: "/home/{{ viper_account_name }}/Desktop/{{ item.name }}.desktop"
    owner: "{{ viper_account_name }}"
    group: "{{ viper_account_name }}"
    mode: a+x
